### ISSUE TITLE
Prob de langue sur page Login

### ISSUE THREAD

**Issue by bapt2001** [contredanse/mfts#11]
ouverture page Login (En), je reclique sur le menu droite pour changer de langue, les messages d'erreur s'affiche encore en anglais.
![capture d ecran 2019-01-24 a 12 22 15](https://user-images.githubusercontent.com/44233527/51675076-ea89bf80-1fd2-11e9-8426-8811667f830b.png)

**Comment by belgattitude** [comment]
It's fine like this
